# Source: fluentbit-resource/templates/fluentbit/fluentbit.yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: lma
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: v1.9.9-kst
spec:
  image: "ghcr.io/openinfradev/fluentbit:v1.9.9-kst"
  positionDB:
    hostPath:
      path: /var/log/flb_kube.db
      type: FileOrCreate
  fluentBitConfigName: fluent-bit-config
  containerLogRealPath: /var/lib/docker/containers
  tolerations:
  - key: node-role.kubernetes.io/master 
    operator: Exists
  - key: node-role.kubernetes.io/node 
    operator: Exists
